### ISSUE TITLE
Vampire prover fails for certain inputs

### ISSUE THREAD

**Issue by sfluegel05** [gavel-tool/python-gavel#10]
I get the error message below when executing the following code:
 
        vampire = prover.registry.get_prover("vampire")()
        fol_proof = vampire.prove(problem=problem)

As a problem, I use the fowl-translations of different chebi-subsets (for example this one [bot-CHEBI_67535-consistent-translated.txt](https://github.com/gavel-tool/python-gavel/files/6496303/bot-CHEBI_67535-consistent-translated.txt)) without conjectures to test them for satisfiability. 
If I make changes that make the ontology inconsistent (for example in this one [bot-CHEBI_67535-inconsistent308-translated.txt](https://github.com/gavel-tool/python-gavel/files/6496304/bot-CHEBI_67535-inconsistent308-translated.txt)), I don't get an error and everything works fine.

Based on the error message I would guess that the line break in the proof vampire return is leading to problems in the tptp-parser. The inconsistent ontologies probably don't fail, because proofs of unsatisfiability are shorter and don't use line breaks. But I am not sure about that and maybe this isn't a gavel-problem at all.

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/lexer.py", line 431, in lex
    yield lexer.next_token(lexer_state)
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/lexer.py", line 354, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal defined for 't' at line 58 col 1

tff(u1062,axiom,
^

Expecting: {'__ANON_6', 'LOGIC'}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sfluegel/.local/lib/python3.8/site-packages/gavel/dialects/tptp/parser.py", line 329, in do
    return list(lark_grammar.parse(string))
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/lark.py", line 495, in parse
    return self.parser.parse(text, start=start)
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 137, in parse
    return self._parse(start, self.make_lexer(text))
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 72, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 129, in parse
    return self.parse_from_state(parser_state)
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 145, in parse_from_state
    raise e
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 135, in parse_from_state
    for token in state.lexer.lex(state):
  File "/home/sfluegel/.local/lib/python3.8/site-packages/lark/lexer.py", line 438, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state.position)
lark.exceptions.UnexpectedToken: Unexpected token Token('__ANON_4', 'tff(u1062,axiom,\n    ~http___www_w3_org_2002_07_owl_Thing(sK21)') at line 58, column 1.
Expected one of: 
	* __ANON_6
	* LOGIC


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sfluegel/.local/lib/python3.8/site-packages/gavel/dialects/tptp/parser.py", line 331, in do
    raise Exception(str(e))
Exception: Unexpected token Token('__ANON_4', 'tff(u1062,axiom,\n    ~http___www_w3_org_2002_07_owl_Thing(sK21)') at line 58, column 1.
Expected one of: 
	* __ANON_6
	* LOGIC

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/simon/OneDrive/Hiwi/python-gavel-owl/src/gavel_owl/consistency_eval.py", line 107, in <module>
    eval_alarm()
  File "/mnt/c/Users/simon/OneDrive/Hiwi/python-gavel-owl/src/gavel_owl/consistency_eval.py", line 86, in eval_alarm
    fol_proof = vampire.prove(problem=problem)
  File "/home/sfluegel/.local/lib/python3.8/site-packages/gavel/prover/base/interface.py", line 43, in prove
    return self._build_proof(
  File "/home/sfluegel/.local/lib/python3.8/site-packages/gavel/prover/base/interface.py", line 115, in _build_proof
    return self.dialect.parse(prover_output)
  File "/home/sfluegel/.local/lib/python3.8/site-packages/gavel/dialects/base/dialect.py", line 40, in parse
    return self._parser.parse(obj, *args, **kwargs)
  File "/home/sfluegel/.local/lib/python3.8/site-packages/gavel/dialects/tptp/parser.py", line 399, in parse
    steps=[
  File "/home/sfluegel/.local/lib/python3.8/site-packages/gavel/dialects/tptp/parser.py", line 399, in <listcomp>
    steps=[
  File "/home/sfluegel/.local/lib/python3.8/site-packages/gavel/dialects/tptp/parser.py", line 375, in parse
    for result in pool.imap(do, inputs):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
Exception: Unexpected token Token('__ANON_4', 'tff(u1062,axiom,\n    ~http___www_w3_org_2002_07_owl_Thing(sK21)') at line 58, column 1.
Expected one of: 
	* __ANON_6
	* LOGIC


Process finished with exit code 1
```

**Comment by MGlauer** [comment]
Hmm... This is very strange. Vampire does not return proper TPTP:

```
% Memory used [KB]: 5245
% Time elapsed: 0.001 s
% ------------------------------
% ------------------------------
% spawned child 14789 with time: 4 (total remaining time 2999)
% dis-10_28_aac=none:add=large:afr=on:afp=4000:afq=1.2:bd=preordered:bsr=on:bce=on:fde=none:gs=on:gsem=off:ile=on:irw=on:lma=on:nm=6:newcnf=on:nwc=1:sas=z3:tha=off:thi=overlap:uwa=all:urr=on_2 on tmps6k_vz
Satisfiable!
% SZS status Satisfiable for tmps6k_vz
% # SZS output start Saturation.
tff(u589,axiom,
    ((~~http___www_w3_org_2002_07_owl_Thing(sK0)) | ~http___www_w3_org_2002_07_owl_Thing(sK0))).
```

The `Satisfiable!` is not a comment. It is a proper line... I guess this is a but in vampire!?
